inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: ~
  TargetRailsVersion: 5.2
  Exclude:
  - 'bin/**/*'
  - 'db/schema.rb'
  - 'db/migrate/*'
  - 'db/fixtures/*'
  - 'Rakefile'
  - 'vendor/**/*'
  - 'config/routes.rb'
  - 'docker/**/*'
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
  - 'config/**/*.rb'
  - '**/*.rake'
  Max: 30
Metrics/LineLength:
  Exclude:
  - 'spec/**/*'
  - 'config/routes/*.rb'
  Max: 160
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 8
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/ClassLength:
  Max: 100
Metrics/ModuleLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Exclude:
  - 'config.ru'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false